-- Tabela de EPCs (Equipamentos de Proteção Coletiva utilizados nas obras)
CREATE TABLE epc (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_epc_nome_lower ON epc (LOWER(nome));

-- Seed de EPCs realistas (ids 1..6)
INSERT INTO epc (id, nome) VALUES
    (1, 'Guarda-corpo'),
    (2, 'Rede de proteção'),
    (3, 'Bandeja salva-vidas'),
    (4, 'Sinalização de segurança'),
    (5, 'Cone de sinalização'),
    (6, 'Extintor de incêndio');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novos EPCs pela API.
SELECT setval(pg_get_serial_sequence('epc', 'id'), (SELECT MAX(id) FROM epc));
