-- Tabela de empresas (empresa vinculada aos colaboradores)
CREATE TABLE empresa (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_empresa_nome_lower ON empresa (LOWER(nome));

-- Seed de empresas realistas (ids 1..6)
INSERT INTO empresa (id, nome) VALUES
    (1, 'Construtora Alvorada'),
    (2, 'Engenharia Horizonte'),
    (3, 'Estrutural Prime'),
    (4, 'Terra Firme Construções'),
    (5, 'Marco Zero Empreendimentos'),
    (6, 'Fundar Engenharia');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novas empresas pela API.
SELECT setval(pg_get_serial_sequence('empresa', 'id'), (SELECT MAX(id) FROM empresa));
