-- Tabela de gestões (áreas de gestão vinculadas aos colaboradores)
CREATE TABLE gestao (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_gestao_nome_lower ON gestao (LOWER(nome));

-- Seed de gestões realistas (ids 1..6)
INSERT INTO gestao (id, nome) VALUES
    (1, 'Gestão de Obras'),
    (2, 'Gestão de Segurança do Trabalho'),
    (3, 'Gestão de Qualidade'),
    (4, 'Gestão de Suprimentos'),
    (5, 'Gestão Administrativa'),
    (6, 'Diretoria Técnica');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novas gestões pela API.
SELECT setval(pg_get_serial_sequence('gestao', 'id'), (SELECT MAX(id) FROM gestao));
