-- Tabela de tipos de solicitação (categorias registradas pelos colaboradores, ex.: manutenção, limpeza)
CREATE TABLE tipo_solicitacao (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_tipo_solicitacao_nome_lower ON tipo_solicitacao (LOWER(nome));

-- Seed de tipos de solicitação realistas (ids 1..6)
INSERT INTO tipo_solicitacao (id, nome) VALUES
    (1, 'Manutenção'),
    (2, 'Limpeza'),
    (3, 'Troca de acomodação'),
    (4, 'Reclamação'),
    (5, 'Solicitação de material'),
    (6, 'Outros');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novos tipos de solicitação pela API.
SELECT setval(pg_get_serial_sequence('tipo_solicitacao', 'id'), (SELECT MAX(id) FROM tipo_solicitacao));
