-- Solicitações abertas por colaboradores para a administração (módulo Solicitações).
CREATE TABLE solicitacao (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_solicitacao_id    BIGINT       NOT NULL,
    colaborador_id         BIGINT       NOT NULL,
    local_id               BIGINT       NOT NULL,
    observacao             VARCHAR(1000) NOT NULL,
    status                 VARCHAR(30)  NOT NULL,
    data_hora_abertura     TIMESTAMP    NOT NULL,
    data_hora_encerramento TIMESTAMP,
    CONSTRAINT fk_solicitacao_tipo        FOREIGN KEY (tipo_solicitacao_id) REFERENCES tipo_solicitacao (id),
    CONSTRAINT fk_solicitacao_colaborador FOREIGN KEY (colaborador_id)      REFERENCES colaborador (id),
    CONSTRAINT fk_solicitacao_local       FOREIGN KEY (local_id)            REFERENCES local (id)
);

CREATE INDEX idx_solicitacao_status      ON solicitacao (status);
CREATE INDEX idx_solicitacao_colaborador ON solicitacao (colaborador_id);
CREATE INDEX idx_solicitacao_local       ON solicitacao (local_id);
CREATE INDEX idx_solicitacao_abertura    ON solicitacao (data_hora_abertura);

-- Seed: usa pares (colaborador, local) de hospedagens reais para respeitar a regra
-- "só abre solicitação em local onde o colaborador está/esteve hospedado".
INSERT INTO solicitacao (tipo_solicitacao_id, colaborador_id, local_id, observacao, status, data_hora_abertura, data_hora_encerramento)
SELECT 1, h.colaborador_id, h.local_id, 'Chuveiro do banheiro está com vazamento, preciso de reparo.',
       'AGUARDANDO_ANALISE', NOW() - INTERVAL '2 days', NULL
FROM hospedagem h ORDER BY h.id LIMIT 1;

INSERT INTO solicitacao (tipo_solicitacao_id, colaborador_id, local_id, observacao, status, data_hora_abertura, data_hora_encerramento)
SELECT 2, h.colaborador_id, h.local_id, 'Solicito uma limpeza extra no alojamento após o fim de semana.',
       'EM_PROCESSAMENTO', NOW() - INTERVAL '5 days', NULL
FROM hospedagem h ORDER BY h.id OFFSET 1 LIMIT 1;

INSERT INTO solicitacao (tipo_solicitacao_id, colaborador_id, local_id, observacao, status, data_hora_abertura, data_hora_encerramento)
SELECT 5, h.colaborador_id, h.local_id, 'Preciso de um novo travesseiro e um cobertor.',
       'FINALIZADA', NOW() - INTERVAL '12 days', NOW() - INTERVAL '9 days'
FROM hospedagem h ORDER BY h.id OFFSET 2 LIMIT 1;

INSERT INTO solicitacao (tipo_solicitacao_id, colaborador_id, local_id, observacao, status, data_hora_abertura, data_hora_encerramento)
SELECT 4, h.colaborador_id, h.local_id, 'Barulho excessivo durante a noite no quarto ao lado.',
       'CANCELADA', NOW() - INTERVAL '8 days', NOW() - INTERVAL '7 days'
FROM hospedagem h ORDER BY h.id OFFSET 3 LIMIT 1;
