-- Histórico (linha do tempo) das trocas de status das solicitações, com observação e data/hora.
CREATE TABLE solicitacao_historico (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitacao_id BIGINT        NOT NULL,
    status         VARCHAR(30)   NOT NULL,
    observacao     VARCHAR(1000),
    data_hora      TIMESTAMP     NOT NULL,
    CONSTRAINT fk_hist_solicitacao FOREIGN KEY (solicitacao_id)
        REFERENCES solicitacao (id) ON DELETE CASCADE
);

CREATE INDEX idx_hist_solicitacao ON solicitacao_historico (solicitacao_id, data_hora);

-- Backfill: evento de abertura para todas as solicitações existentes.
INSERT INTO solicitacao_historico (solicitacao_id, status, observacao, data_hora)
SELECT id, 'AGUARDANDO_ANALISE', NULL, data_hora_abertura
FROM solicitacao;

-- Backfill: evento do status atual (quando já saiu de "aguardando"), usando o encerramento quando houver.
INSERT INTO solicitacao_historico (solicitacao_id, status, observacao, data_hora)
SELECT id, status, NULL, COALESCE(data_hora_encerramento, data_hora_abertura)
FROM solicitacao
WHERE status <> 'AGUARDANDO_ANALISE';
