-- Rateio de cada gasto por EPC (snapshot no lançamento): proporção de colaboradores
-- hospedados ativos no local, por EPC, dividindo o custo total (quantidade x valor).
CREATE TABLE gasto_rateio (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gasto_id   BIGINT        NOT NULL,
    epc_id     BIGINT        NOT NULL,
    epc_nome   VARCHAR(120)  NOT NULL,
    pessoas    INTEGER       NOT NULL,
    percentual NUMERIC(5, 2) NOT NULL,
    valor      NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_rateio_gasto FOREIGN KEY (gasto_id) REFERENCES gasto (id) ON DELETE CASCADE
);

CREATE INDEX idx_gasto_rateio_gasto ON gasto_rateio (gasto_id);

-- Backfill dos gastos existentes com base nos hospedados ativos atuais de cada local.
WITH dist AS (
    SELECT h.local_id, c.epc_id, COUNT(*) AS pessoas
    FROM hospedagem h
    JOIN colaborador c ON c.id = h.colaborador_id
    WHERE h.data_saida IS NULL
    GROUP BY h.local_id, c.epc_id
),
tot AS (
    SELECT local_id, SUM(pessoas) AS total FROM dist GROUP BY local_id
)
INSERT INTO gasto_rateio (gasto_id, epc_id, epc_nome, pessoas, percentual, valor)
SELECT g.id, d.epc_id, e.nome, d.pessoas,
       ROUND(d.pessoas * 100.0 / t.total, 2),
       ROUND((g.quantidade * g.valor) * d.pessoas / t.total, 2)
FROM gasto g
JOIN dist d ON d.local_id = g.local_id
JOIN tot t ON t.local_id = g.local_id
JOIN epc e ON e.id = d.epc_id;
