-- Tabela de colaboradores (módulo Colaboradores do ObraStay)
CREATE TABLE colaborador (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL,
    sexo  VARCHAR(20)  NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_colaborador_nome_lower ON colaborador (LOWER(nome));
