-- Usuários do sistema (autenticação). Senha em hash BCrypt.
CREATE TABLE usuario (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(120) NOT NULL,
    email      VARCHAR(160) NOT NULL UNIQUE,
    senha      VARCHAR(100) NOT NULL,
    criado_em  TIMESTAMP    NOT NULL DEFAULT now()
);
