-- Status dos Locais: define se o local pode ou não liberar novas hospedagens,
-- vínculo obrigatório no Local e histórico de mudanças de status (auditoria).

-- 1) Tabela de status
CREATE TABLE status_local (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(80) NOT NULL,
    hospedagem_liberada BOOLEAN     NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX ux_status_local_nome_lower ON status_local (LOWER(nome));

-- Seed inicial: só "Disponível" libera hospedagem.
INSERT INTO status_local (nome, hospedagem_liberada) VALUES
    ('Disponível',    TRUE),
    ('Bloqueado',     FALSE),
    ('Em manutenção', FALSE);

-- 2) Vínculo obrigatório no Local (backfill dos existentes com "Disponível")
ALTER TABLE local ADD COLUMN status_id BIGINT;

UPDATE local
SET status_id = (SELECT id FROM status_local WHERE nome = 'Disponível' LIMIT 1)
WHERE status_id IS NULL;

ALTER TABLE local ALTER COLUMN status_id SET NOT NULL;
ALTER TABLE local ADD CONSTRAINT fk_local_status
    FOREIGN KEY (status_id) REFERENCES status_local (id);
CREATE INDEX idx_local_status ON local (status_id);

-- 3) Histórico de mudanças de status do local (auditoria).
-- Guarda o id do status E um snapshot do nome (de/para), pois é registro histórico:
-- deve continuar legível mesmo se o status for renomeado ou removido depois.
CREATE TABLE local_status_historico (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id             BIGINT       NOT NULL,
    status_anterior_id   BIGINT,
    status_anterior_nome VARCHAR(80),
    status_novo_id       BIGINT       NOT NULL,
    status_novo_nome     VARCHAR(80)  NOT NULL,
    observacao           VARCHAR(500),
    usuario_nome         VARCHAR(120),
    criado_em            TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_hist_local FOREIGN KEY (local_id) REFERENCES local (id) ON DELETE CASCADE
);

CREATE INDEX idx_local_status_hist_local ON local_status_historico (local_id, criado_em DESC);

-- Entrada inicial do histórico para os locais já existentes.
INSERT INTO local_status_historico
    (local_id, status_anterior_id, status_anterior_nome, status_novo_id, status_novo_nome, observacao, usuario_nome)
SELECT l.id, NULL, NULL, s.id, s.nome, 'Status inicial (migração)', NULL
FROM local l
JOIN status_local s ON s.id = l.status_id;
