-- Orçamento de Mobiliário: lista de itens (móveis/eletros) para mobiliar uma casa.
-- Cada item guarda quanto é fixo na casa e quanto é por quarto — assim a simulação
-- de custo por nº de quartos (regra futura) atende de 1 até N quartos sem limite.

CREATE TABLE orcamento_mobiliario (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    criado_em TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_orcamento_mobiliario_nome_lower ON orcamento_mobiliario (LOWER(nome));

CREATE TABLE orcamento_mobiliario_item (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orcamento_id          BIGINT         NOT NULL,
    nome                  VARCHAR(160)   NOT NULL,
    preco_unitario        NUMERIC(12, 2) NOT NULL,
    quantidade_fixa       INTEGER        NOT NULL DEFAULT 0,
    quantidade_por_quarto INTEGER        NOT NULL DEFAULT 0,
    ordem                 INTEGER        NOT NULL DEFAULT 0,
    CONSTRAINT fk_orcmob_item_orcamento FOREIGN KEY (orcamento_id)
        REFERENCES orcamento_mobiliario (id) ON DELETE CASCADE
);

CREATE INDEX idx_orcmob_item_orcamento ON orcamento_mobiliario_item (orcamento_id);
