-- Nº de quartos do Local (base da regra de mobiliário) e a lista de itens de mobília
-- do próprio Local (cópia independente, editável, feita a partir de um Orçamento de Mobiliário).

ALTER TABLE local ADD COLUMN quartos INTEGER;
UPDATE local SET quartos = 1 WHERE quartos IS NULL;
ALTER TABLE local ALTER COLUMN quartos SET NOT NULL;

CREATE TABLE local_mobilia_item (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id              BIGINT         NOT NULL,
    nome                  VARCHAR(160)   NOT NULL,
    preco_unitario        NUMERIC(12, 2) NOT NULL,
    quantidade_fixa       INTEGER        NOT NULL DEFAULT 0,
    quantidade_por_quarto INTEGER        NOT NULL DEFAULT 0,
    ordem                 INTEGER        NOT NULL DEFAULT 0,
    CONSTRAINT fk_local_mobilia_local FOREIGN KEY (local_id)
        REFERENCES local (id) ON DELETE CASCADE
);

CREATE INDEX idx_local_mobilia_local ON local_mobilia_item (local_id);
