-- Seed de colaboradores para a demo (paginação e filtros já funcionam de imediato)
INSERT INTO colaborador (nome, sexo) VALUES
    ('Ana Beatriz Souza',        'FEMININO'),
    ('Carlos Eduardo Oliveira',  'MASCULINO'),
    ('Mariana Ferreira Lima',    'FEMININO'),
    ('João Pedro Almeida',       'MASCULINO'),
    ('Fernanda Costa Ribeiro',   'FEMININO'),
    ('Rafael Santos Pereira',    'MASCULINO'),
    ('Juliana Rodrigues Melo',   'FEMININO'),
    ('Bruno Henrique Carvalho',  'MASCULINO'),
    ('Camila Nunes Barbosa',     'FEMININO'),
    ('Lucas Gabriel Martins',    'MASCULINO'),
    ('Patrícia Gomes Araújo',    'FEMININO'),
    ('Thiago Moreira Cardoso',   'MASCULINO'),
    ('Aline Cristina Teixeira',  'FEMININO'),
    ('Gustavo Henrique Rocha',   'MASCULINO'),
    ('Larissa Andrade Pinto',    'FEMININO'),
    ('Marcelo Vieira Dias',      'MASCULINO'),
    ('Beatriz Correia Fonseca',  'FEMININO'),
    ('Felipe Augusto Ramos',     'MASCULINO'),
    ('Vanessa Lopes Cavalcanti', 'FEMININO'),
    ('Rodrigo Silveira Monteiro','MASCULINO'),
    ('Débora Cristina Freitas',  'FEMININO'),
    ('Anderson Luiz Barros',     'MASCULINO'),
    ('Renata Aparecida Machado', 'FEMININO'),
    ('Diego Fernandes Nogueira', 'MASCULINO');
