-- Controle de acesso por perfil (RBAC): perfis com permissões por tela e ação.
-- Migração ADITIVA e segura em produção: cria as tabelas, semeia os perfis, adiciona
-- usuario.perfil_id com backfill de TODOS os usuários atuais para "Administrador"
-- (ninguém perde acesso) e só então marca a coluna como NOT NULL.

-- 1) Perfil. acesso_total = concede tudo (Administrador). sistema = protegido (não editar/excluir).
CREATE TABLE perfil (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(80)  NOT NULL,
    descricao    VARCHAR(240),
    acesso_total BOOLEAN      NOT NULL DEFAULT FALSE,
    sistema      BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX ux_perfil_nome_lower ON perfil (LOWER(nome));

-- 2) Permissões concedidas ao perfil (par tela + ação). Presença = concedido.
CREATE TABLE perfil_permissao (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id BIGINT      NOT NULL,
    tela      VARCHAR(40) NOT NULL,
    acao      VARCHAR(20) NOT NULL,
    CONSTRAINT fk_perfilperm_perfil FOREIGN KEY (perfil_id)
        REFERENCES perfil (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_perfil_permissao ON perfil_permissao (perfil_id, tela, acao);
CREATE INDEX idx_perfilperm_perfil ON perfil_permissao (perfil_id);

-- 3) Perfis iniciais. Administrador tem acesso total e é protegido.
--    As permissões de Gestor e Consulta são semeadas pelo DataInitializer (a partir do
--    catálogo em código), evitando duplicar o catálogo aqui e o risco de divergência.
INSERT INTO perfil (nome, descricao, acesso_total, sistema) VALUES
    ('Administrador', 'Acesso total ao sistema.',                              TRUE,  TRUE),
    ('Gestor',        'Operação completa, exceto gestão de usuários e perfis.', FALSE, FALSE),
    ('Consulta',      'Somente leitura e exportação.',                          FALSE, FALSE);

-- 4) Vincula o perfil ao usuário. Backfill: todo usuário atual vira Administrador.
ALTER TABLE usuario ADD COLUMN perfil_id BIGINT;

UPDATE usuario
   SET perfil_id = (SELECT id FROM perfil WHERE nome = 'Administrador')
 WHERE perfil_id IS NULL;

ALTER TABLE usuario ALTER COLUMN perfil_id SET NOT NULL;
ALTER TABLE usuario ADD CONSTRAINT fk_usuario_perfil FOREIGN KEY (perfil_id) REFERENCES perfil (id);
