-- Trilha de auditoria (append-only): logins, logout e ações sensíveis (criar/editar/excluir
-- e ações especiais) dos usuários. Guarda também IP e navegador. Migração aditiva.
--
-- tela/acao/evento são gravados como TEXTO (não FK/enum no banco) de propósito: o log é
-- histórico imutável e não pode quebrar se um enum de código mudar no futuro.
CREATE TABLE log_auditoria (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT,
    usuario_email  VARCHAR(160),
    evento         VARCHAR(20)  NOT NULL,          -- LOGIN, LOGOUT, ACAO
    tela           VARCHAR(40),                    -- para evento ACAO (chave da tela)
    acao           VARCHAR(30),                    -- para evento ACAO (ex.: CRIAR, EDITAR)
    detalhe        VARCHAR(255),                   -- ex.: "PUT /api/colaboradores/13" ou motivo da falha
    sucesso        BOOLEAN      NOT NULL DEFAULT TRUE,
    status_http    INTEGER,
    ip             VARCHAR(45),                    -- comporta IPv6
    user_agent     VARCHAR(255),
    data_hora      TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_logaud_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);

CREATE INDEX idx_logaud_data ON log_auditoria (data_hora);
CREATE INDEX idx_logaud_usuario ON log_auditoria (usuario_id);
CREATE INDEX idx_logaud_evento ON log_auditoria (evento);
