-- Notificações das ações principais (Entrada, Saída, Nova Solicitação) para o sino do topo.
-- Entrega filtrada por permissão (feito na query) e por autor (não notifica quem executou).
-- Leitura: por item (notificacao_leitura) + marca geral por data (usuario.notificacoes_lidas_em).
CREATE TABLE notificacao (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo              VARCHAR(20)  NOT NULL,          -- ENTRADA, SAIDA, SOLICITACAO
    tela              VARCHAR(40)  NOT NULL,          -- chave da tela (hospedagens, solicitacoes)
    titulo            VARCHAR(200) NOT NULL,
    rota              VARCHAR(200) NOT NULL,          -- destino ao clicar
    autor_usuario_id  BIGINT,                         -- quem executou (nulo = autoatendimento/kiosk)
    data_hora         TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_notif_autor FOREIGN KEY (autor_usuario_id) REFERENCES usuario (id) ON DELETE SET NULL
);

CREATE INDEX idx_notif_data ON notificacao (data_hora);
CREATE INDEX idx_notif_tela ON notificacao (tela);

-- Leitura individual por usuário (presença = lida).
CREATE TABLE notificacao_leitura (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     BIGINT NOT NULL,
    notificacao_id BIGINT NOT NULL,
    CONSTRAINT fk_notiflido_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_notiflido_notif FOREIGN KEY (notificacao_id) REFERENCES notificacao (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_notificacao_leitura ON notificacao_leitura (usuario_id, notificacao_id);
CREATE INDEX idx_notiflido_usuario ON notificacao_leitura (usuario_id);

-- Marca de "li tudo até esta data" por usuário (para "marcar todas como lidas").
ALTER TABLE usuario ADD COLUMN notificacoes_lidas_em TIMESTAMP;
