-- Tabela de funções (módulo Funções do ObraStay)
CREATE TABLE funcao (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_funcao_nome_lower ON funcao (LOWER(nome));

-- Seed de funções realistas de construção civil (ids 1..10)
INSERT INTO funcao (id, nome) VALUES
    (1,  'Pedreiro'),
    (2,  'Servente'),
    (3,  'Mestre de obras'),
    (4,  'Carpinteiro'),
    (5,  'Armador'),
    (6,  'Eletricista'),
    (7,  'Encanador'),
    (8,  'Pintor'),
    (9,  'Almoxarife'),
    (10, 'Engenheiro civil');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novas funções pela API.
SELECT setval(pg_get_serial_sequence('funcao', 'id'), (SELECT MAX(id) FROM funcao));
