-- Tabela de locais de acomodação (módulo Locais do ObraStay)
CREATE TABLE local (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(30)  NOT NULL UNIQUE,
    nome         VARCHAR(120) NOT NULL,
    capacidade   INTEGER      NOT NULL,
    cep          VARCHAR(9)   NOT NULL,
    logradouro   VARCHAR(150) NOT NULL,
    numero       VARCHAR(20)  NOT NULL,
    complemento  VARCHAR(100),
    bairro       VARCHAR(100) NOT NULL,
    cidade       VARCHAR(100) NOT NULL,
    uf           VARCHAR(2)   NOT NULL
);

-- Índices para buscas case-insensitive (LOWER(...) LIKE %valor%)
CREATE INDEX idx_local_nome_lower   ON local (LOWER(nome));
CREATE INDEX idx_local_codigo_lower ON local (LOWER(codigo));
CREATE INDEX idx_local_cidade_lower ON local (LOWER(cidade));

-- Seed de locais realistas (ids 1..6)
INSERT INTO local (id, codigo, nome, capacidade, cep, logradouro, numero, complemento, bairro, cidade, uf) VALUES
    (1, 'ALJ-001', 'Alojamento Central',     40, '01001-000', 'Praça da Sé',                '100', NULL,        'Sé',            'São Paulo',      'SP'),
    (2, 'HTL-002', 'Hotel Obra Rio',          25, '20040-002', 'Avenida Rio Branco',         '156', '5º andar',  'Centro',        'Rio de Janeiro', 'RJ'),
    (3, 'CSA-003', 'Casa Savassi',            12, '30130-010', 'Rua da Bahia',               '1200', NULL,       'Centro',        'Belo Horizonte', 'MG'),
    (4, 'ALJ-004', 'Alojamento Litoral',      60, '40020-000', 'Avenida Sete de Setembro',   '500', NULL,        'Dois de Julho', 'Salvador',       'BA'),
    (5, 'HTL-005', 'Hotel Curitiba Centro',   30, '80010-010', 'Rua XV de Novembro',         '300', 'Bloco B',   'Centro',        'Curitiba',       'PR'),
    (6, 'CSA-006', 'Casa Asa Norte',          15, '70040-010', 'SBN Quadra 1',               '2',   NULL,        'Asa Norte',     'Brasília',       'DF');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novos locais pela API.
SELECT setval(pg_get_serial_sequence('local', 'id'), (SELECT MAX(id) FROM local));
