-- Tabela de locadoras (empresa responsável pela locação dos locais, ex.: imobiliárias)
CREATE TABLE locadora (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL
);

-- Índice para busca case-insensitive por nome (LOWER(nome) LIKE %valor%)
CREATE INDEX idx_locadora_nome_lower ON locadora (LOWER(nome));

-- Seed de locadoras realistas (ids 1..6)
INSERT INTO locadora (id, nome) VALUES
    (1, 'Imobiliária Horizonte'),
    (2, 'Predial Nova Era'),
    (3, 'Aluga Fácil Imóveis'),
    (4, 'Center Locações'),
    (5, 'Morar Bem Imobiliária'),
    (6, 'Prime Hospedagens');

-- Sincroniza a sequence de identidade após o seed com ids explícitos,
-- evitando colisão de PK ao criar novas locadoras pela API.
SELECT setval(pg_get_serial_sequence('locadora', 'id'), (SELECT MAX(id) FROM locadora));
