-- Tabela de hospedagens: registra entradas e saídas de colaboradores em locais
-- (módulo Gestão de Hospedagem do ObraStay). data_saida NULL = hospedagem ATIVA.
CREATE TABLE hospedagem (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colaborador_id BIGINT NOT NULL REFERENCES colaborador(id),
    local_id       BIGINT NOT NULL REFERENCES local(id),
    data_entrada   DATE   NOT NULL,
    data_saida     DATE,
    observacao     VARCHAR(255)
);

-- Índices para os filtros e joins mais comuns
CREATE INDEX idx_hospedagem_local ON hospedagem(local_id);
CREATE INDEX idx_hospedagem_colaborador ON hospedagem(colaborador_id);

-- Reforça no banco a regra "1 hospedagem ativa por colaborador":
-- só pode existir uma linha com data_saida NULL por colaborador.
CREATE UNIQUE INDEX uk_hospedagem_colab_ativa ON hospedagem(colaborador_id) WHERE data_saida IS NULL;

-- Seed (respeitando: cada colaborador com no máximo 1 ativa). Datas relativas a CURRENT_DATE.
INSERT INTO hospedagem (colaborador_id, local_id, data_entrada, data_saida, observacao) VALUES
    (1, 1, CURRENT_DATE - 20, NULL, NULL),
    (2, 1, CURRENT_DATE - 15, NULL, NULL),
    (3, 1, CURRENT_DATE - 10, NULL, NULL),
    (5, 2, CURRENT_DATE - 12, NULL, NULL),
    (7, 2, CURRENT_DATE - 5,  NULL, NULL),
    (9, 3, CURRENT_DATE - 8,  NULL, NULL),
    (4, 1, CURRENT_DATE - 40, CURRENT_DATE - 10, 'Transferido'),
    (6, 2, CURRENT_DATE - 30, CURRENT_DATE - 3,  NULL);
