-- Tabela de contratos de locação: vincula um local a uma locadora por um período
-- (módulo Gestão de Contratos do ObraStay). O status (VIGENTE/AGENDADO/ENCERRADO)
-- é derivado da data atual em relação a [data_inicio, data_fim].
CREATE TABLE contrato (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(40) NOT NULL UNIQUE,
    local_id    BIGINT NOT NULL REFERENCES local(id),
    locadora_id BIGINT NOT NULL REFERENCES locadora(id),
    data_inicio DATE NOT NULL,
    data_fim    DATE NOT NULL
);

-- Índices para os filtros e joins mais comuns
CREATE INDEX idx_contrato_local ON contrato(local_id);
CREATE INDEX idx_contrato_codigo_lower ON contrato(LOWER(codigo));

-- Seed variado (datas relativas a CURRENT_DATE); locais 1..6 e locadoras 1..6 existem.
-- Sem ids explícitos (identity gera). Respeita não-sobreposição por local.
INSERT INTO contrato (codigo, local_id, locadora_id, data_inicio, data_fim) VALUES
    ('CT-2024-001', 1, 1, CURRENT_DATE - 400, CURRENT_DATE - 35),   -- local 1: encerrado (ano anterior)
    ('CT-2025-001', 1, 1, CURRENT_DATE - 34,  CURRENT_DATE + 330),  -- local 1: vigente (verde, ~330 dias)
    ('CT-2025-002', 2, 2, CURRENT_DATE - 350, CURRENT_DATE + 20),   -- local 2: vigente vencendo (âmbar, 20 dias)
    ('CT-2025-003', 3, 3, CURRENT_DATE - 100, CURRENT_DATE + 200),  -- local 3: vigente (verde)
    ('CT-2024-004', 4, 4, CURRENT_DATE - 400, CURRENT_DATE - 10);   -- local 4: vencido (sem vigente)
-- locais 5 e 6 ficam sem contrato de propósito (demo "sem contrato vigente").
