-- Tabela de gastos (lançamentos de despesa) por local (módulo Gestão de Gastos).
-- O valor é UNITÁRIO; o total de cada gasto = quantidade x valor. Sem categoria.
CREATE TABLE gasto (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id   BIGINT NOT NULL REFERENCES local(id),
    nome       VARCHAR(120) NOT NULL,
    quantidade NUMERIC(12,3) NOT NULL,
    valor      NUMERIC(12,2) NOT NULL,
    data       DATE NOT NULL
);

-- Índices para os filtros e joins mais comuns
CREATE INDEX idx_gasto_local ON gasto(local_id);
CREATE INDEX idx_gasto_data ON gasto(data);

-- Seed variado (datas relativas a CURRENT_DATE; locais 1..4 existem). Sem ids explícitos.
INSERT INTO gasto (local_id, nome, quantidade, valor, data) VALUES
    (1, 'Cimento CP-II (saco 50kg)', 40,  38.90,  CURRENT_DATE - 25),
    (1, 'Tinta acrílica (lata 18L)', 6,   289.90, CURRENT_DATE - 12),
    (1, 'Mão de obra pintura',       1,   1500.00,CURRENT_DATE - 5),
    (1, 'Conta de energia',          1,   842.35, CURRENT_DATE - 2),
    (2, 'Aluguel do mês',            1,   3500.00,CURRENT_DATE - 20),
    (2, 'Material hidráulico',       15,  47.50,  CURRENT_DATE - 8),
    (3, 'Areia média (m³)',          10.5,120.00, CURRENT_DATE - 15),
    (3, 'Gás de cozinha (botijão)',  4,   115.00, CURRENT_DATE - 3);
