import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  // Rotas com parâmetro: renderizadas sob demanda no servidor (sem prerender).
  { path: 'auto-atendimento/:localId', renderMode: RenderMode.Server },
  { path: 'colaboradores/:id/editar', renderMode: RenderMode.Server },
  { path: 'funcoes/:id/editar', renderMode: RenderMode.Server },
  { path: 'epcs/:id/editar', renderMode: RenderMode.Server },
  { path: 'empresas/:id/editar', renderMode: RenderMode.Server },
  { path: 'gestoes/:id/editar', renderMode: RenderMode.Server },
  { path: 'tipos-solicitacao/:id/editar', renderMode: RenderMode.Server },
  { path: 'locais/:id/editar', renderMode: RenderMode.Server },
  { path: 'status-locais/:id/editar', renderMode: RenderMode.Server },
  { path: 'orcamentos-mobiliario/:id/editar', renderMode: RenderMode.Server },
  { path: 'locadoras/:id/editar', renderMode: RenderMode.Server },
  { path: 'hospedagens/local/:id', renderMode: RenderMode.Server },
  { path: 'hospedagens/local/:id/entrada', renderMode: RenderMode.Server },
  { path: 'contratos/local/:id', renderMode: RenderMode.Server },
  { path: 'contratos/local/:id/novo', renderMode: RenderMode.Server },
  { path: 'contratos/editar/:id', renderMode: RenderMode.Server },
  { path: 'gastos/local/:id', renderMode: RenderMode.Server },
  { path: 'gastos/local/:id/novo', renderMode: RenderMode.Server },
  { path: 'gastos/editar/:id', renderMode: RenderMode.Server },
  { path: 'solicitacoes/:id/editar', renderMode: RenderMode.Server },
  { path: 'usuarios/:id/editar', renderMode: RenderMode.Server },
  { path: 'perfis/:id/editar', renderMode: RenderMode.Server },
  // Modo somente-leitura (Visualizar) — também renderizado sob demanda no servidor.
  { path: 'colaboradores/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'funcoes/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'epcs/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'empresas/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'gestoes/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'locais/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'status-locais/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'orcamentos-mobiliario/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'locadoras/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'tipos-solicitacao/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'usuarios/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'perfis/:id/visualizar', renderMode: RenderMode.Server },
  { path: 'contratos/visualizar/:id', renderMode: RenderMode.Server },
  { path: 'gastos/visualizar/:id', renderMode: RenderMode.Server },
  { path: 'solicitacoes/:id/visualizar', renderMode: RenderMode.Server },
  // Demais rotas (estáticas) continuam pré-renderizadas.
  { path: '**', renderMode: RenderMode.Prerender },
];
